name: Create and Commit ZIP

on:
  push:
    branches:
      - master

jobs:
  create_and_commit_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create archive
      run: |
        zip -r alive-plugin.zip test/

    - name: Move archive to repository
      run: |
        mkdir -p $GITHUB_WORKSPACE/archive
        mv alive-plugin.zip $GITHUB_WORKSPACE/archive/

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit ZIP
      run: |
        git add archive/alive-plugin.zip
        git commit -m "Add ZIP archive"
        git push
